pipeline {
    options { timestamps() }
    agent none

    stages {
        stage('Check scm') {
            agent any
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Building ... ${BUILD_NUMBER}"
                echo "Build completed"
            }
        }

        stage('Test') {
            agent { 
                docker { 
                    image 'python:3.12-alpine' 
                    args '-u root'            
                }
            }
            steps {
                
                sh 'apk add --update python3 py3-pip'
                
                
                sh 'python3 -m venv /venv'
                sh '/venv/bin/pip install unittest-xml-reporting'

                
                sh '/venv/bin/python Test.py'
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
                success {
                    echo "Testing successful"
                }
                failure {
                    echo "Tests failed"
                }
            }
        }
    }
}